-- Helmet requests. Additive: one new table, nothing else touched.
--
-- A player types what they would like their helmet to be, from the More page
-- or from their own player card, and the row lands here. Andrew sees every row
-- with no seen_at the next time he opens the app, on a card, and GOT IT stamps
-- seen_at. Nothing is deleted, so an old request can still be read back.

create table if not exists helmet_requests (
  id          bigint generated by default as identity primary key,
  player_id   uuid references players(id),
  player_name text not null,
  message     text not null,
  created_at  timestamptz not null default now(),
  seen_at     timestamptz
);

comment on table helmet_requests is
  'What a player would like their helmet to be. seen_at is set when Andrew has read it.';

-- The app is a private league behind a name picker and the same anon key
-- already writes picks and flags, so this adds no access that was not there.
alter table helmet_requests enable row level security;

drop policy if exists "helmet requests insert" on helmet_requests;
create policy "helmet requests insert" on helmet_requests
  for insert with check (true);

drop policy if exists "helmet requests select" on helmet_requests;
create policy "helmet requests select" on helmet_requests
  for select using (true);

drop policy if exists "helmet requests update" on helmet_requests;
create policy "helmet requests update" on helmet_requests
  for update using (true) with check (true);
