// Generates src/nationList.js: every flag a player can fly.
//
//   node scripts/nation-list.mjs
//
// Country names come from Intl.DisplayNames at BUILD time, not at run time, so
// every device shows the same name regardless of its own ICU data. The output
// is committed; this script only runs when the list needs changing.
import { writeFileSync } from "node:fs";

const dn = new Intl.DisplayNames(["en"], { type: "region" });

// Intl hands back more than ISO 3166-1: exceptional reservations, the EU, and
// the private-use codes. None of those is a place somebody is from.
const NOT_A_COUNTRY = new Set([
  "AC", "CP", "CQ", "DG", "EA", "EU", "EZ", "IC", "TA", "UN", "QO", "XA", "XB", "ZZ",
]);

const countries = [];
for (let a = 65; a <= 90; a++) {
  for (let b = 65; b <= 90; b++) {
    const code = String.fromCharCode(a) + String.fromCharCode(b);
    if (NOT_A_COUNTRY.has(code)) continue;
    let name;
    try { name = dn.of(code); } catch (e) { continue; }
    if (!name || name === code) continue;
    countries.push({ code, name });
  }
}
countries.sort((x, y) => x.name.localeCompare(y.name));

// States carry a US- prefix so a state code can never collide with a country
// code. AL is Albania and Alabama otherwise.
const STATES = [
  ["AL", "Alabama"], ["AK", "Alaska"], ["AZ", "Arizona"], ["AR", "Arkansas"],
  ["CA", "California"], ["CO", "Colorado"], ["CT", "Connecticut"], ["DE", "Delaware"],
  ["FL", "Florida"], ["GA", "Georgia"], ["HI", "Hawaii"], ["ID", "Idaho"],
  ["IL", "Illinois"], ["IN", "Indiana"], ["IA", "Iowa"], ["KS", "Kansas"],
  ["KY", "Kentucky"], ["LA", "Louisiana"], ["ME", "Maine"], ["MD", "Maryland"],
  ["MA", "Massachusetts"], ["MI", "Michigan"], ["MN", "Minnesota"], ["MS", "Mississippi"],
  ["MO", "Missouri"], ["MT", "Montana"], ["NE", "Nebraska"], ["NV", "Nevada"],
  ["NH", "New Hampshire"], ["NJ", "New Jersey"], ["NM", "New Mexico"], ["NY", "New York"],
  ["NC", "North Carolina"], ["ND", "North Dakota"], ["OH", "Ohio"], ["OK", "Oklahoma"],
  ["OR", "Oregon"], ["PA", "Pennsylvania"], ["RI", "Rhode Island"], ["SC", "South Carolina"],
  ["SD", "South Dakota"], ["TN", "Tennessee"], ["TX", "Texas"], ["UT", "Utah"],
  ["VT", "Vermont"], ["VA", "Virginia"], ["WA", "Washington"], ["WV", "West Virginia"],
  ["WI", "Wisconsin"], ["WY", "Wyoming"],
  ["DC", "Washington, D.C."],
];
const TERRITORIES = [
  ["PR", "Puerto Rico"], ["GU", "Guam"], ["VI", "U.S. Virgin Islands"],
  ["AS", "American Samoa"], ["MP", "Northern Mariana Islands"],
];

const out = `// Every flag a player can fly. Generated by scripts/nation-list.mjs.
// Do not hand-edit: run the script.
//
// Country codes are ISO 3166-1 alpha-2. States and US territories carry a
// "US-" prefix, because AL is Albania and Alabama and only one of them can have
// the bare code.
//
// "" is no flag, which is a real choice and the default for anybody who has not
// picked one.

export const COUNTRIES = ${JSON.stringify(countries, null, 0).replace(/},{/g, "},\n  {").replace(/^\[/, "[\n  ").replace(/\]$/, ",\n]")};

export const STATES = [
${STATES.map(([c, n]) => `  { code: "US-${c}", name: ${JSON.stringify(n)} },`).join("\n")}
];

export const TERRITORIES = [
${TERRITORIES.map(([c, n]) => `  { code: "US-${c}", name: ${JSON.stringify(n)} },`).join("\n")}
];

export const NO_FLAG = { code: "", name: "No flag" };

// One list for the picker, in the order it reads best: nothing, then countries,
// then the states and territories under their own headings.
export const GROUPS = [
  { label: "", items: [NO_FLAG] },
  { label: "Countries", items: COUNTRIES },
  { label: "US states", items: STATES },
  { label: "US territories", items: TERRITORIES },
];

export const ALL = [NO_FLAG, ...COUNTRIES, ...STATES, ...TERRITORIES];
export const NAME_OF = Object.fromEntries(ALL.map(x => [x.code, x.name]));
`;

writeFileSync("src/nationList.js", out);
console.log(`countries ${countries.length}, states ${STATES.length}, territories ${TERRITORIES.length}, total ${countries.length + STATES.length + TERRITORIES.length + 1}`);
