-- Second-half calendar and schedule. Generated by scripts/schedule2.mjs.
-- Additive only. Nothing is deleted and no scored round is touched.
-- Run the whole file as one transaction.

BEGIN;

-- 1. Malaysia joins the calendar as round 16, so the old rounds 16-22 shift up
--    one and the season ends at 23. Shifted in two hops so no two races ever
--    hold the same round number mid-statement.
UPDATE races SET round = round + 1000 WHERE season = 2026 AND round >= 16;
UPDATE races SET round = round - 999  WHERE season = 2026 AND round >= 1016;

INSERT INTO races (season, round, race_name, circuit, race_date, pick_deadline, top_drivers, mid_drivers, pit_stop_question)
VALUES (2026, 16, 'Bahrain Grand Prix', 'Sepang International Circuit', '2026-10-04', '2026-10-03T00:00:00+00:00', '{}', '{}', '');

-- 2. The second-half draw, rounds 12 to 22. Round 23 at Abu Dhabi is left
--    undrawn and gets seeded once round 22 is scored.
--    home_team_id is the OVER seat (Admin.jsx:547). Home carries no other meaning.
INSERT INTO schedule (race_id, home_team_id, away_team_id) VALUES
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), '2343928e-bdf3-415a-9f0a-ef3b6af5793f', '0a09b0a7-8d2c-451a-9541-29b3046aaee3'),  -- R12  Drivetex OVER v UNDER Van City Corsa
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), '579bad3e-bbc9-42f2-9371-22abd9da04d4', 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385'),  -- R12  XLIX Racing Team OVER v UNDER Cal Aggie Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a', 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21'),  -- R12  Juicero Silicon Valley OVER v UNDER HomeworkTubes.Com
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), '44aabae5-10ac-47e4-8314-27a67adec475', '4ce965b1-70bf-43db-a3b0-6585be8d8b5e'),  -- R12  East Bay Racing OVER v UNDER Peloton Aubergine
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), '27ccc53b-cca4-4b6b-a166-7ed81b11c86f', '8c6bc36d-54ab-4df5-85f8-564128000041'),  -- R12  Meatballs OVER v UNDER Cascadia Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f', '9a1eeebb-53f4-4435-842a-835fcb9c416f'),  -- R12  Cougar Autosport OVER v UNDER TNT Roku F5 Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385', '0a09b0a7-8d2c-451a-9541-29b3046aaee3'),  -- R13  Cal Aggie Racing OVER v UNDER Van City Corsa
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a', '2343928e-bdf3-415a-9f0a-ef3b6af5793f'),  -- R13  Juicero Silicon Valley OVER v UNDER Drivetex
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), '4ce965b1-70bf-43db-a3b0-6585be8d8b5e', '579bad3e-bbc9-42f2-9371-22abd9da04d4'),  -- R13  Peloton Aubergine OVER v UNDER XLIX Racing Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21', '27ccc53b-cca4-4b6b-a166-7ed81b11c86f'),  -- R13  HomeworkTubes.Com OVER v UNDER Meatballs
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), '9a1eeebb-53f4-4435-842a-835fcb9c416f', '44aabae5-10ac-47e4-8314-27a67adec475'),  -- R13  TNT Roku F5 Team OVER v UNDER East Bay Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f', '8c6bc36d-54ab-4df5-85f8-564128000041'),  -- R13  Cougar Autosport OVER v UNDER Cascadia Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), '0a09b0a7-8d2c-451a-9541-29b3046aaee3', '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a'),  -- R14  Van City Corsa OVER v UNDER Juicero Silicon Valley
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385', '4ce965b1-70bf-43db-a3b0-6585be8d8b5e'),  -- R14  Cal Aggie Racing OVER v UNDER Peloton Aubergine
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), '27ccc53b-cca4-4b6b-a166-7ed81b11c86f', '2343928e-bdf3-415a-9f0a-ef3b6af5793f'),  -- R14  Meatballs OVER v UNDER Drivetex
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), '9a1eeebb-53f4-4435-842a-835fcb9c416f', '579bad3e-bbc9-42f2-9371-22abd9da04d4'),  -- R14  TNT Roku F5 Team OVER v UNDER XLIX Racing Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21', 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f'),  -- R14  HomeworkTubes.Com OVER v UNDER Cougar Autosport
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), '8c6bc36d-54ab-4df5-85f8-564128000041', '44aabae5-10ac-47e4-8314-27a67adec475'),  -- R14  Cascadia Motorsport OVER v UNDER East Bay Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), '4ce965b1-70bf-43db-a3b0-6585be8d8b5e', '0a09b0a7-8d2c-451a-9541-29b3046aaee3'),  -- R15  Peloton Aubergine OVER v UNDER Van City Corsa
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a', '27ccc53b-cca4-4b6b-a166-7ed81b11c86f'),  -- R15  Juicero Silicon Valley OVER v UNDER Meatballs
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), '9a1eeebb-53f4-4435-842a-835fcb9c416f', 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385'),  -- R15  TNT Roku F5 Team OVER v UNDER Cal Aggie Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f', '2343928e-bdf3-415a-9f0a-ef3b6af5793f'),  -- R15  Cougar Autosport OVER v UNDER Drivetex
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), '8c6bc36d-54ab-4df5-85f8-564128000041', '579bad3e-bbc9-42f2-9371-22abd9da04d4'),  -- R15  Cascadia Motorsport OVER v UNDER XLIX Racing Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21', '44aabae5-10ac-47e4-8314-27a67adec475'),  -- R15  HomeworkTubes.Com OVER v UNDER East Bay Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), '0a09b0a7-8d2c-451a-9541-29b3046aaee3', '27ccc53b-cca4-4b6b-a166-7ed81b11c86f'),  -- R16  Van City Corsa OVER v UNDER Meatballs
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), '4ce965b1-70bf-43db-a3b0-6585be8d8b5e', '9a1eeebb-53f4-4435-842a-835fcb9c416f'),  -- R16  Peloton Aubergine OVER v UNDER TNT Roku F5 Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a', 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f'),  -- R16  Juicero Silicon Valley OVER v UNDER Cougar Autosport
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385', '8c6bc36d-54ab-4df5-85f8-564128000041'),  -- R16  Cal Aggie Racing OVER v UNDER Cascadia Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), '2343928e-bdf3-415a-9f0a-ef3b6af5793f', '44aabae5-10ac-47e4-8314-27a67adec475'),  -- R16  Drivetex OVER v UNDER East Bay Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), '579bad3e-bbc9-42f2-9371-22abd9da04d4', 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21'),  -- R16  XLIX Racing Team OVER v UNDER HomeworkTubes.Com
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), '0a09b0a7-8d2c-451a-9541-29b3046aaee3', '9a1eeebb-53f4-4435-842a-835fcb9c416f'),  -- R17  Van City Corsa OVER v UNDER TNT Roku F5 Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), '27ccc53b-cca4-4b6b-a166-7ed81b11c86f', 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f'),  -- R17  Meatballs OVER v UNDER Cougar Autosport
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), '8c6bc36d-54ab-4df5-85f8-564128000041', '4ce965b1-70bf-43db-a3b0-6585be8d8b5e'),  -- R17  Cascadia Motorsport OVER v UNDER Peloton Aubergine
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), '44aabae5-10ac-47e4-8314-27a67adec475', '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a'),  -- R17  East Bay Racing OVER v UNDER Juicero Silicon Valley
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21', 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385'),  -- R17  HomeworkTubes.Com OVER v UNDER Cal Aggie Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), '579bad3e-bbc9-42f2-9371-22abd9da04d4', '2343928e-bdf3-415a-9f0a-ef3b6af5793f'),  -- R17  XLIX Racing Team OVER v UNDER Drivetex
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f', '0a09b0a7-8d2c-451a-9541-29b3046aaee3'),  -- R18  Cougar Autosport OVER v UNDER Van City Corsa
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), '8c6bc36d-54ab-4df5-85f8-564128000041', '9a1eeebb-53f4-4435-842a-835fcb9c416f'),  -- R18  Cascadia Motorsport OVER v UNDER TNT Roku F5 Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), '44aabae5-10ac-47e4-8314-27a67adec475', '27ccc53b-cca4-4b6b-a166-7ed81b11c86f'),  -- R18  East Bay Racing OVER v UNDER Meatballs
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21', '4ce965b1-70bf-43db-a3b0-6585be8d8b5e'),  -- R18  HomeworkTubes.Com OVER v UNDER Peloton Aubergine
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), '579bad3e-bbc9-42f2-9371-22abd9da04d4', '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a'),  -- R18  XLIX Racing Team OVER v UNDER Juicero Silicon Valley
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), '2343928e-bdf3-415a-9f0a-ef3b6af5793f', 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385'),  -- R18  Drivetex OVER v UNDER Cal Aggie Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), '8c6bc36d-54ab-4df5-85f8-564128000041', '0a09b0a7-8d2c-451a-9541-29b3046aaee3'),  -- R19  Cascadia Motorsport OVER v UNDER Van City Corsa
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), '44aabae5-10ac-47e4-8314-27a67adec475', 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f'),  -- R19  East Bay Racing OVER v UNDER Cougar Autosport
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), '9a1eeebb-53f4-4435-842a-835fcb9c416f', 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21'),  -- R19  TNT Roku F5 Team OVER v UNDER HomeworkTubes.Com
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), '27ccc53b-cca4-4b6b-a166-7ed81b11c86f', '579bad3e-bbc9-42f2-9371-22abd9da04d4'),  -- R19  Meatballs OVER v UNDER XLIX Racing Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), '2343928e-bdf3-415a-9f0a-ef3b6af5793f', '4ce965b1-70bf-43db-a3b0-6585be8d8b5e'),  -- R19  Drivetex OVER v UNDER Peloton Aubergine
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385', '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a'),  -- R19  Cal Aggie Racing OVER v UNDER Juicero Silicon Valley
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '44aabae5-10ac-47e4-8314-27a67adec475', '0a09b0a7-8d2c-451a-9541-29b3046aaee3'),  -- R20  East Bay Racing OVER v UNDER Van City Corsa
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '8c6bc36d-54ab-4df5-85f8-564128000041', 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21'),  -- R20  Cascadia Motorsport OVER v UNDER HomeworkTubes.Com
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '579bad3e-bbc9-42f2-9371-22abd9da04d4', 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f'),  -- R20  XLIX Racing Team OVER v UNDER Cougar Autosport
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '9a1eeebb-53f4-4435-842a-835fcb9c416f', '2343928e-bdf3-415a-9f0a-ef3b6af5793f'),  -- R20  TNT Roku F5 Team OVER v UNDER Drivetex
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385', '27ccc53b-cca4-4b6b-a166-7ed81b11c86f'),  -- R20  Cal Aggie Racing OVER v UNDER Meatballs
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '4ce965b1-70bf-43db-a3b0-6585be8d8b5e', '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a'),  -- R20  Peloton Aubergine OVER v UNDER Juicero Silicon Valley
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), '0a09b0a7-8d2c-451a-9541-29b3046aaee3', 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21'),  -- R21  Van City Corsa OVER v UNDER HomeworkTubes.Com
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), '579bad3e-bbc9-42f2-9371-22abd9da04d4', '44aabae5-10ac-47e4-8314-27a67adec475'),  -- R21  XLIX Racing Team OVER v UNDER East Bay Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), '2343928e-bdf3-415a-9f0a-ef3b6af5793f', '8c6bc36d-54ab-4df5-85f8-564128000041'),  -- R21  Drivetex OVER v UNDER Cascadia Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f', 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385'),  -- R21  Cougar Autosport OVER v UNDER Cal Aggie Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), '9a1eeebb-53f4-4435-842a-835fcb9c416f', '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a'),  -- R21  TNT Roku F5 Team OVER v UNDER Juicero Silicon Valley
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), '4ce965b1-70bf-43db-a3b0-6585be8d8b5e', '27ccc53b-cca4-4b6b-a166-7ed81b11c86f'),  -- R21  Peloton Aubergine OVER v UNDER Meatballs
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), '0a09b0a7-8d2c-451a-9541-29b3046aaee3', '579bad3e-bbc9-42f2-9371-22abd9da04d4'),  -- R22  Van City Corsa OVER v UNDER XLIX Racing Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), '2343928e-bdf3-415a-9f0a-ef3b6af5793f', 'fc7843e9-bf07-493f-a9bf-59c6ce2f3a21'),  -- R22  Drivetex OVER v UNDER HomeworkTubes.Com
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), '44aabae5-10ac-47e4-8314-27a67adec475', 'f3eab88a-5d25-4e3b-b7fc-2aa7a9ea4385'),  -- R22  East Bay Racing OVER v UNDER Cal Aggie Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), '8ae6c08b-ce0e-4383-91c2-ceb17ba3db1a', '8c6bc36d-54ab-4df5-85f8-564128000041'),  -- R22  Juicero Silicon Valley OVER v UNDER Cascadia Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), 'b4a23ce2-0b92-4db3-9ec8-20f7735d212f', '4ce965b1-70bf-43db-a3b0-6585be8d8b5e'),  -- R22  Cougar Autosport OVER v UNDER Peloton Aubergine
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), '27ccc53b-cca4-4b6b-a166-7ed81b11c86f', '9a1eeebb-53f4-4435-842a-835fcb9c416f'),  -- R22  Meatballs OVER v UNDER TNT Roku F5 Team
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), 'a602540b-92f4-48f0-bff2-67e74fba1e67', '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a'),  -- R12  El Camino Rapido OVER v UNDER Garra Dynamics
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a', '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba'),  -- R12  Stalloni 1851 OVER v UNDER TJ Premium
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), '5c4087ab-d297-43c8-a132-d212ed0e1190', 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43'),  -- R12  Wildcat Motors OVER v UNDER Shoey Time! w/ Max and Danny
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), '8743272f-21a4-443c-af8b-819ea11615a2', '113cbd29-f5b3-4311-a4ef-0b053404719d'),  -- R12  Luxor Motorsport OVER v UNDER Bronco SCUderia
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), '4c3cda25-74f1-4884-9e85-d45fff114e71', 'f3e74436-4bb4-4be6-b3b5-3829e29e032a'),  -- R12  Magic Kingdom Racing OVER v UNDER Scuderia Iskandaraya
  ((SELECT id FROM races WHERE season = 2026 AND round = 12), 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5', '611053aa-8e7d-4b64-b37a-c34c3a59dd5f'),  -- R12  Aggie Slipstream OVER v UNDER Prestissimo Veloce
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), 'a602540b-92f4-48f0-bff2-67e74fba1e67', '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba'),  -- R13  El Camino Rapido OVER v UNDER TJ Premium
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a', 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43'),  -- R13  Garra Dynamics OVER v UNDER Shoey Time! w/ Max and Danny
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), '8743272f-21a4-443c-af8b-819ea11615a2', 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a'),  -- R13  Luxor Motorsport OVER v UNDER Stalloni 1851
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), '5c4087ab-d297-43c8-a132-d212ed0e1190', 'f3e74436-4bb4-4be6-b3b5-3829e29e032a'),  -- R13  Wildcat Motors OVER v UNDER Scuderia Iskandaraya
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), '113cbd29-f5b3-4311-a4ef-0b053404719d', 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5'),  -- R13  Bronco SCUderia OVER v UNDER Aggie Slipstream
  ((SELECT id FROM races WHERE season = 2026 AND round = 13), '611053aa-8e7d-4b64-b37a-c34c3a59dd5f', '4c3cda25-74f1-4884-9e85-d45fff114e71'),  -- R13  Prestissimo Veloce OVER v UNDER Magic Kingdom Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43', 'a602540b-92f4-48f0-bff2-67e74fba1e67'),  -- R14  Shoey Time! w/ Max and Danny OVER v UNDER El Camino Rapido
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba', '8743272f-21a4-443c-af8b-819ea11615a2'),  -- R14  TJ Premium OVER v UNDER Luxor Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), 'f3e74436-4bb4-4be6-b3b5-3829e29e032a', '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a'),  -- R14  Scuderia Iskandaraya OVER v UNDER Garra Dynamics
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5', 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a'),  -- R14  Aggie Slipstream OVER v UNDER Stalloni 1851
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), '611053aa-8e7d-4b64-b37a-c34c3a59dd5f', '5c4087ab-d297-43c8-a132-d212ed0e1190'),  -- R14  Prestissimo Veloce OVER v UNDER Wildcat Motors
  ((SELECT id FROM races WHERE season = 2026 AND round = 14), '4c3cda25-74f1-4884-9e85-d45fff114e71', '113cbd29-f5b3-4311-a4ef-0b053404719d'),  -- R14  Magic Kingdom Racing OVER v UNDER Bronco SCUderia
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), '8743272f-21a4-443c-af8b-819ea11615a2', 'a602540b-92f4-48f0-bff2-67e74fba1e67'),  -- R15  Luxor Motorsport OVER v UNDER El Camino Rapido
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43', 'f3e74436-4bb4-4be6-b3b5-3829e29e032a'),  -- R15  Shoey Time! w/ Max and Danny OVER v UNDER Scuderia Iskandaraya
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba', 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5'),  -- R15  TJ Premium OVER v UNDER Aggie Slipstream
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), '611053aa-8e7d-4b64-b37a-c34c3a59dd5f', '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a'),  -- R15  Prestissimo Veloce OVER v UNDER Garra Dynamics
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a', '4c3cda25-74f1-4884-9e85-d45fff114e71'),  -- R15  Stalloni 1851 OVER v UNDER Magic Kingdom Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 15), '113cbd29-f5b3-4311-a4ef-0b053404719d', '5c4087ab-d297-43c8-a132-d212ed0e1190'),  -- R15  Bronco SCUderia OVER v UNDER Wildcat Motors
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), 'f3e74436-4bb4-4be6-b3b5-3829e29e032a', 'a602540b-92f4-48f0-bff2-67e74fba1e67'),  -- R16  Scuderia Iskandaraya OVER v UNDER El Camino Rapido
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5', '8743272f-21a4-443c-af8b-819ea11615a2'),  -- R16  Aggie Slipstream OVER v UNDER Luxor Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), '611053aa-8e7d-4b64-b37a-c34c3a59dd5f', 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43'),  -- R16  Prestissimo Veloce OVER v UNDER Shoey Time! w/ Max and Danny
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), '4c3cda25-74f1-4884-9e85-d45fff114e71', '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba'),  -- R16  Magic Kingdom Racing OVER v UNDER TJ Premium
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a', '113cbd29-f5b3-4311-a4ef-0b053404719d'),  -- R16  Garra Dynamics OVER v UNDER Bronco SCUderia
  ((SELECT id FROM races WHERE season = 2026 AND round = 16), '5c4087ab-d297-43c8-a132-d212ed0e1190', 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a'),  -- R16  Wildcat Motors OVER v UNDER Stalloni 1851
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5', 'a602540b-92f4-48f0-bff2-67e74fba1e67'),  -- R17  Aggie Slipstream OVER v UNDER El Camino Rapido
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), 'f3e74436-4bb4-4be6-b3b5-3829e29e032a', '611053aa-8e7d-4b64-b37a-c34c3a59dd5f'),  -- R17  Scuderia Iskandaraya OVER v UNDER Prestissimo Veloce
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), '4c3cda25-74f1-4884-9e85-d45fff114e71', '8743272f-21a4-443c-af8b-819ea11615a2'),  -- R17  Magic Kingdom Racing OVER v UNDER Luxor Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43', '113cbd29-f5b3-4311-a4ef-0b053404719d'),  -- R17  Shoey Time! w/ Max and Danny OVER v UNDER Bronco SCUderia
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba', '5c4087ab-d297-43c8-a132-d212ed0e1190'),  -- R17  TJ Premium OVER v UNDER Wildcat Motors
  ((SELECT id FROM races WHERE season = 2026 AND round = 17), 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a', '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a'),  -- R17  Stalloni 1851 OVER v UNDER Garra Dynamics
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), 'a602540b-92f4-48f0-bff2-67e74fba1e67', '611053aa-8e7d-4b64-b37a-c34c3a59dd5f'),  -- R18  El Camino Rapido OVER v UNDER Prestissimo Veloce
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), '4c3cda25-74f1-4884-9e85-d45fff114e71', 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5'),  -- R18  Magic Kingdom Racing OVER v UNDER Aggie Slipstream
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), 'f3e74436-4bb4-4be6-b3b5-3829e29e032a', '113cbd29-f5b3-4311-a4ef-0b053404719d'),  -- R18  Scuderia Iskandaraya OVER v UNDER Bronco SCUderia
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), '5c4087ab-d297-43c8-a132-d212ed0e1190', '8743272f-21a4-443c-af8b-819ea11615a2'),  -- R18  Wildcat Motors OVER v UNDER Luxor Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a', 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43'),  -- R18  Stalloni 1851 OVER v UNDER Shoey Time! w/ Max and Danny
  ((SELECT id FROM races WHERE season = 2026 AND round = 18), '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a', '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba'),  -- R18  Garra Dynamics OVER v UNDER TJ Premium
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), 'a602540b-92f4-48f0-bff2-67e74fba1e67', '4c3cda25-74f1-4884-9e85-d45fff114e71'),  -- R19  El Camino Rapido OVER v UNDER Magic Kingdom Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), '113cbd29-f5b3-4311-a4ef-0b053404719d', '611053aa-8e7d-4b64-b37a-c34c3a59dd5f'),  -- R19  Bronco SCUderia OVER v UNDER Prestissimo Veloce
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), '5c4087ab-d297-43c8-a132-d212ed0e1190', 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5'),  -- R19  Wildcat Motors OVER v UNDER Aggie Slipstream
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a', 'f3e74436-4bb4-4be6-b3b5-3829e29e032a'),  -- R19  Stalloni 1851 OVER v UNDER Scuderia Iskandaraya
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), '8743272f-21a4-443c-af8b-819ea11615a2', '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a'),  -- R19  Luxor Motorsport OVER v UNDER Garra Dynamics
  ((SELECT id FROM races WHERE season = 2026 AND round = 19), '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba', 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43'),  -- R19  TJ Premium OVER v UNDER Shoey Time! w/ Max and Danny
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '113cbd29-f5b3-4311-a4ef-0b053404719d', 'a602540b-92f4-48f0-bff2-67e74fba1e67'),  -- R20  Bronco SCUderia OVER v UNDER El Camino Rapido
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '4c3cda25-74f1-4884-9e85-d45fff114e71', '5c4087ab-d297-43c8-a132-d212ed0e1190'),  -- R20  Magic Kingdom Racing OVER v UNDER Wildcat Motors
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a', '611053aa-8e7d-4b64-b37a-c34c3a59dd5f'),  -- R20  Stalloni 1851 OVER v UNDER Prestissimo Veloce
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a', 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5'),  -- R20  Garra Dynamics OVER v UNDER Aggie Slipstream
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba', 'f3e74436-4bb4-4be6-b3b5-3829e29e032a'),  -- R20  TJ Premium OVER v UNDER Scuderia Iskandaraya
  ((SELECT id FROM races WHERE season = 2026 AND round = 20), '8743272f-21a4-443c-af8b-819ea11615a2', 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43'),  -- R20  Luxor Motorsport OVER v UNDER Shoey Time! w/ Max and Danny
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), 'a602540b-92f4-48f0-bff2-67e74fba1e67', '5c4087ab-d297-43c8-a132-d212ed0e1190'),  -- R21  El Camino Rapido OVER v UNDER Wildcat Motors
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), '113cbd29-f5b3-4311-a4ef-0b053404719d', 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a'),  -- R21  Bronco SCUderia OVER v UNDER Stalloni 1851
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a', '4c3cda25-74f1-4884-9e85-d45fff114e71'),  -- R21  Garra Dynamics OVER v UNDER Magic Kingdom Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), '611053aa-8e7d-4b64-b37a-c34c3a59dd5f', '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba'),  -- R21  Prestissimo Veloce OVER v UNDER TJ Premium
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43', 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5'),  -- R21  Shoey Time! w/ Max and Danny OVER v UNDER Aggie Slipstream
  ((SELECT id FROM races WHERE season = 2026 AND round = 21), 'f3e74436-4bb4-4be6-b3b5-3829e29e032a', '8743272f-21a4-443c-af8b-819ea11615a2'),  -- R21  Scuderia Iskandaraya OVER v UNDER Luxor Motorsport
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), 'a602540b-92f4-48f0-bff2-67e74fba1e67', 'b9eb80e4-13ef-41d6-adff-1c8e64270c6a'),  -- R22  El Camino Rapido OVER v UNDER Stalloni 1851
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), '2cfbbd19-61c8-4c6a-87c1-6367a3f5483a', '5c4087ab-d297-43c8-a132-d212ed0e1190'),  -- R22  Garra Dynamics OVER v UNDER Wildcat Motors
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), '16ff8643-cd10-4ad5-9118-e4e50fb4a0ba', '113cbd29-f5b3-4311-a4ef-0b053404719d'),  -- R22  TJ Premium OVER v UNDER Bronco SCUderia
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), 'd9e7da52-4a19-48e0-8c5d-4cfce49f5f43', '4c3cda25-74f1-4884-9e85-d45fff114e71'),  -- R22  Shoey Time! w/ Max and Danny OVER v UNDER Magic Kingdom Racing
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), '8743272f-21a4-443c-af8b-819ea11615a2', '611053aa-8e7d-4b64-b37a-c34c3a59dd5f'),  -- R22  Luxor Motorsport OVER v UNDER Prestissimo Veloce
  ((SELECT id FROM races WHERE season = 2026 AND round = 22), 'bfd3f733-9e00-4aec-8b30-42ac5f98f0d5', 'f3e74436-4bb4-4be6-b3b5-3829e29e032a');  -- R22  Aggie Slipstream OVER v UNDER Scuderia Iskandaraya

COMMIT;

-- Checks to run after. Expect: 23 races ending at Abu Dhabi, 264 schedule rows,
-- 12 matchups per round for rounds 12-22, and no round with a repeated team.
-- SELECT round, race_name, race_date FROM races WHERE season = 2026 ORDER BY round;
-- SELECT r.round, count(*) FROM schedule s JOIN races r ON r.id = s.race_id GROUP BY r.round ORDER BY r.round;
