// News feed stories, newest first.
// authorType: "human" (that player's avatar) | "auto" (F5 logo)
// Body blocks: {t:"p"} paragraph | {t:"h"} header | {t:"sub"} subheader
//              {t:"note"} callout | {t:"m"} matchup | {t:"chart"} ranked dot plot
// Team cards resolve logos by `name`, which must match the teams table exactly.
// `label` is display-only, for names too long for a half-width box.

const M = (title, a, b, story) => ({ t: "m", title, story, teams: [a, b] });

export const NEWS = [
  {
    id: "r11-preview",
    headline: "Round 11 Preview: It's Moving Day.",
    author: "Andrew Ishak",
    authorType: "human",
    date: "2026-07-21",
    dek: "We close out the first half of the season at the Hungaroring in Budapest.",
    body: [
      { t: "p", text: "We close out the first half of the season at the Hungaroring in Budapest. Here's what's on the line as teams try to ensure their spot in the Championship division." },
      { t: "p", text: "As we enter the last round of the first half, most teams are looking at the prospect of promotion to the Championship Division, or relegation to the Second Division." },
      { t: "h", text: "Championship" },
      { t: "sub", text: "Bottom four relegated" },
      { t: "note", title: "Six teams, two survive", text: "The top six are all mathematically safe, which leaves Garra, El Camino, Stalloni, Cascadia, Wildcat and Bronco fighting over the last two places. Four of those six go down. Only Garra and Bronco play each other, so the rest spend Sunday watching the scoreboard." },

      { t: "standings", lineAfter: 8, lineLabel: "Relegation line", rows: [
        { pos: 1,  name: "Van City Corsa",        pts: 119, zone: "ok" , chip: "TITLE", ctone: "good" },
        { pos: 2,  name: "Juicero Silicon Valley", pts: 118, zone: "ok" , chip: "TITLE", ctone: "good" },
        { pos: 3,  name: "XLIX Racing Team",      pts: 115, zone: "ok" , chip: "TITLE", ctone: "good" },
        { pos: 4,  name: "Cougar Autosport",      pts: 100, zone: "ok" , chip: "TITLE", ctone: "good" },
        { pos: 5,  name: "Drivetex",              pts: 89,  zone: "ok" , chip: "EXPOSED", ctone: "warn" },
        { pos: 6,  name: "East Bay Racing",       pts: 86,  zone: "ok" , chip: "EXPOSED", ctone: "warn" },
        { pos: 7,  name: "Garra Dynamics",        pts: 77,  zone: "ok" , chip: "WIN = SAFE", ctone: "warn" },
        { pos: 8,  name: "El Camino Rapido",      pts: 66,  zone: "mp", badge: "matchup position" , chip: "DANGER", ctone: "warn" },
        { pos: 9,  name: "Stalloni 1851",         pts: 64,  zone: "drop" , chip: "DANGER", ctone: "warn" },
        { pos: 10, name: "Cascadia Motorsport",   pts: 64,  zone: "drop" , chip: "DANGER", ctone: "warn" },
        { pos: 11, name: "Wildcat Motors",        pts: 58,  zone: "drop" , chip: "WIN + HELP", ctone: "bad" },
        { pos: 12, name: "Bronco SCUderia",       pts: 54,  zone: "drop" , chip: "WIN + HELP", ctone: "bad" },
      ]},

      { t: "p", text: "I asked Claude to simulate the Hungary race 50,000 times. Here are the odds of each team in the Championship Division staying up for the second half." },
      { t: "odds", title: "Championship", sub: "Chance of staying up", rows: [
        { name: "Van City Corsa", p: 100 }, { name: "Juicero Silicon Valley", p: 100 },
        { name: "XLIX Racing Team", p: 100 }, { name: "Cougar Autosport", p: 100 },
        { name: "Drivetex", p: 99.8 }, { name: "East Bay Racing", p: 99.3 },
        { name: "Garra Dynamics", p: 78.6 }, { name: "El Camino Rapido", p: 35.5 },
        { name: "Stalloni 1851", p: 27.8 }, { name: "Cascadia Motorsport", p: 21.2 },
        { name: "Wildcat Motors", p: 3.2 }, { name: "Bronco SCUderia", p: 0.1 },
      ]},
      { t: "p", text: "Garra are the story at 78.6%. Everyone else in that drop zone is closer to a coin flip than a plan, and Bronco's 0.1% is not quite zero, which is the nicest thing that can be said about it." },
      { t: "note", title: "How the odds were made", text: "Each team's Hungary score is drawn at random from their own ten scores this season, so form and consistency both carry through. BOX BOX is assigned at random, one team plus five and the other minus one, at the rate it has actually been scored. What it does not model: teams playing BOX BOX strategically, and the fact that everyone's scores move together on a chaotic race weekend. A good guide, not gospel." },

      M("Garra Dynamics vs Bronco SCUderia",
        { name: "Garra Dynamics", playing: "trying to stay in the Championship Division.", meta: "7th, 77 pts", tag: "WIN AND SAFE", tone: "warn", can: "4th to 11th",
          players: ["Ryan Kohli", "Francisco Soldavini"],
          notes: ["Any win at all keeps them up. Even the smallest win is worth 8 points, putting them on 85, and only one other team in the zone can possibly reach that.",
                  "Lose and they are still alive, but no longer in control. On 77 to 83, they need at least four of the other five danger teams to fall short.",
                  "The only team in the drop zone that decides its own fate."] },
        { name: "Bronco SCUderia", playing: "trying to stay in the Championship Division.", meta: "12th, 54 pts", tag: "MUST WIN + HELP", tone: "bad", can: "7th to 12th",
          players: ["Alicia Cho", "Maggie Mudge"],
          notes: ["No result guarantees safety, and a narrow win is not enough. They need at least 12 points from beating Garra, reaching 66. A minimum win of 8 leaves them on 62, behind even a losing El Camino.",
                  "Even then they need El Camino, Stalloni and Cascadia to all fall short.",
                  "The fixture is the opportunity. Beating Garra drags the team directly above the line back down into it, so a win counts twice.",
                  "Lose and they are relegated."] },
        { text: "Current Broncos against former Broncos. Nothing like closing out the half against your own alumni." }),

      M("Van City Corsa vs Cascadia Motorsport",
        { name: "Van City Corsa", playing: "going for the first half championship.", meta: "1st, 119 pts", tag: "TITLE FIGHT", tone: "good", can: "1st to 4th",
          players: ["Rafik Zarifa", "Mena Yousef"],
          notes: ["Safe even losing with zero. One point clear at the top, so this is about the first half championship and nothing else. They are favourites for it at 46%."] },
        { name: "Cascadia Motorsport", playing: "trying to stay in the Championship Division.", meta: "10th, 64 pts", tag: "IN DANGER", tone: "warn", can: "5th to 12th",
          players: ["Martin Nobar", "Ronnie Nobar"],
          notes: ["Only a maximum win of 25 points would guarantee safety. That takes them to 89 and clear of everyone.",
                  "A smaller win keeps them alive. 15 points would put them on 79, which holds only if at most one of El Camino, Stalloni or a winning Bronco climbs past it.",
                  "Surviving a loss would need at least 2 points from it, and would need El Camino, Stalloni and Wildcat to all lose as well.",
                  "The hardest draw of anyone in the drop zone."] },
        { text: "Last season's Canadian teammates, now at opposite ends of the table. Could Van City send Cascadia down?" }),

      M("Juicero Silicon Valley vs El Camino Rapido",
        { name: "Juicero Silicon Valley", playing: "chasing the first half championship from one point back.", meta: "2nd, 118 pts", tag: "TITLE FIGHT", tone: "good", can: "1st to 4th",
          players: ["George Fahmy", "Kerolos Nakhla"],
          notes: ["One point behind Van City, so the first half championship is live, and they take it 31% of the time. Relegation is impossible."] },
        { name: "El Camino Rapido", playing: "trying to stay in the Championship Division.", meta: "8th, 66 pts", tag: "IN DANGER", tone: "warn", can: "5th to 12th",
          players: ["Harold Gutmann", "Paul Kohli"],
          notes: ["Only a maximum win of 25 points would guarantee safety, taking them to 91.",
                  "A smaller win keeps them alive. 12 points would put them on 78, which holds only if at most one of Stalloni, Cascadia or a winning Bronco gets past. A minimum win of 8 leaves them on 74, below even a losing Garra.",
                  "Surviving a loss would need Stalloni, Cascadia and Wildcat to all lose too, with Stalloni taking no more than 2 points from theirs.",
                  "Best placed of the danger teams, and the hardest opponent of the four watching the scoreboard."] },
        { text: "A Silicon Valley derby to close out the half." }),

      M("East Bay Racing vs Wildcat Motors",
        { name: "East Bay Racing", playing: "already safe, but guarding against the Matchup Position swap.", meta: "6th, 86 pts", tag: "EXPOSED AT 8TH", tone: "warn", can: "4th to 8th",
          players: ["Joe Hanna", "Zack Girgis"],
          notes: ["Cannot be relegated automatically. Wildcat tops out below East Bay's floor.",
                  "But they can finish 8th, and 8th is the one seat the Matchup Position targets. Their 78.4 average sits a tenth of a point ahead of Cal Aggie's 78.3.",
                  "Out of the title race, so beyond that tenth of a point this is second half preparation."] },
        { name: "Wildcat Motors", playing: "trying to stay in the Championship Division.", meta: "11th, 58 pts", tag: "MUST WIN + HELP", tone: "bad", can: "7th to 12th",
          players: ["Aditya Satish", "Theo Ishak"],
          notes: ["No result guarantees safety. Even a maximum win, taking them to 83, can be beaten if two of Garra, El Camino, Stalloni and Cascadia clear it.",
                  "They need a win worth at least 8 points and then two of the teams above them to lose.",
                  "Lose and they are relegated outright."] }),

      M("Drivetex vs Stalloni 1851",
        { name: "Drivetex", playing: "already safe, but guarding against the Matchup Position swap.", meta: "5th, 89 pts", tag: "EXPOSED AT 8TH", tone: "warn", can: "4th to 8th",
          players: ["Nick Brody", "Joe McGlynn"],
          notes: ["Cannot be relegated automatically. Stalloni tops out level with them, and the teams below cannot all clear 89 at once.",
                  "But 8th is still reachable, which leaves them open to the Matchup Position. Their 79.2 average is the highest of any team that could land there, so they are the best protected of the exposed.",
                  "Out of the title race, so this is a second half tune-up."] },
        { name: "Stalloni 1851", playing: "trying to stay in the Championship Division.", meta: "9th, 64 pts", tag: "IN DANGER", tone: "warn", can: "5th to 12th",
          players: ["Jack Civitts", "Scott Schertler"],
          notes: ["Only a maximum win of 25 points would guarantee safety, putting them on 89.",
                  "A smaller win keeps them alive. 15 points would put them on 79, ahead of a losing Garra, though still catchable if two of El Camino, Cascadia or Bronco go past.",
                  "Surviving a loss would need at least 2 points from it, and would need El Camino, Cascadia and Wildcat to all lose."] }),

      M("XLIX Racing Team vs Cougar Autosport",
        { name: "XLIX Racing Team", playing: "chasing the first half championship.", meta: "3rd, 115 pts", tag: "TITLE FIGHT", tone: "good", can: "1st to 4th",
          players: ["Krista Nabil", "Moses Abdelshaid"],
          notes: ["Win big and they take the first half championship, which happens 21% of the time. Cannot fall below 4th."] },
        { name: "Cougar Autosport", playing: "an outside shot at the first half championship.", meta: "4th, 100 pts", tag: "TITLE FIGHT", tone: "good", can: "1st to 7th",
          players: ["Heather Ishak", "Lucia Thompson"],
          notes: ["A maximum win puts them on 125 and takes the first half championship, though that is only a 2% shot. Even at 100 flat they cannot be relegated."] },
        { text: "The only matchup where both teams are safe, and the one with the first half championship riding on it." }),

      { t: "h", text: "Second Division" },
      { t: "sub", text: "Top four promoted" },
      { t: "note", title: "Five teams, one or two places", text: "Meatballs, TNT Roku and HomeworkTubes are already up. That leaves Peloton, Cal Aggie, Luxor, Shoey and Magic Kingdom fighting over the last automatic promotion place, and possibly a second one through the Matchup Position. Here is the good part: four of those five are playing each other. Peloton against Cal Aggie, Luxor against Shoey. It turns the first two matchups below into playoff ties." },

      { t: "standings", lineAfter: 4, lineLabel: "Promotion line", rows: [
        { pos: 1,  name: "Meatballs",             pts: 143, zone: "ok" , chip: "UP", ctone: "good" },
        { pos: 2,  name: "TNT Roku F5 Team",      pts: 121, zone: "ok" , chip: "UP", ctone: "good" },
        { pos: 3,  name: "HomeworkTubes.Com",     pts: 117, zone: "ok" , chip: "UP", ctone: "good" },
        { pos: 4,  name: "Peloton Aubergine",     pts: 97,  zone: "ok" , chip: "IN HUNT", ctone: "warn" },
        { pos: 5,  name: "Cal Aggie Racing",      pts: 93,  zone: "mp", badge: "matchup position" , chip: "MUST WIN", ctone: "bad" },
        { pos: 6,  name: "Luxor Motorsport",      pts: 85,  zone: "none" , chip: "WIN BIG", ctone: "bad" },
        { pos: 7,  name: "Shoey Time!",           pts: 82,  zone: "none" , chip: "WIN BIG", ctone: "bad" },
        { pos: 8,  name: "Magic Kingdom Racing",  pts: 78,  zone: "none" , chip: "LONG SHOT", ctone: "warn" },
        { pos: 9,  name: "TJ Premium",            pts: 65,  zone: "none" , chip: "DOWN", ctone: "dead" },
        { pos: 10, name: "Prestissimo Veloce",    pts: 47,  zone: "none" , chip: "DOWN", ctone: "dead" },
        { pos: 11, name: "Aggie Slipstream",      pts: 46,  zone: "none" , chip: "DOWN", ctone: "dead" },
        { pos: 12, name: "Scuderia Iskandaraya",  pts: 36,  zone: "none" , chip: "DOWN", ctone: "dead" },
      ]},

      { t: "p", text: "I asked Claude to simulate the Hungary race 50,000 times. Here are the odds of each team in the Second Division being promoted for the second half." },
      { t: "odds", title: "Second Division", sub: "Chance of going up", rows: [
        { name: "Meatballs", p: 100 }, { name: "TNT Roku F5 Team", p: 100 },
        { name: "HomeworkTubes.Com", p: 100 }, { name: "Cal Aggie Racing", p: 66.5 },
        { name: "Peloton Aubergine", p: 63.5 }, { name: "Luxor Motorsport", p: 3.1 },
        { name: "Shoey Time!", p: 0.9 }, { name: "Magic Kingdom Racing", p: 0.5 },
        { name: "TJ Premium", p: 0 }, { name: "Prestissimo Veloce", p: 0 },
        { name: "Aggie Slipstream", p: 0 }, { name: "Scuderia Iskandaraya", p: 0 },
      ]},
      { t: "p", text: "Cal Aggie and Peloton add up to more than one promotion place between them, and that is not a rounding error. The Matchup Position swap fires in 34.5% of simulations, so five teams go up and five come down more often than one round in three. Both of them can be promoted in the same scenario." },

      M("Peloton Aubergine vs Cal Aggie Racing",
        { name: "Peloton Aubergine", playing: "trying to earn promotion to the Championship Division.", meta: "4th, 97 pts", tag: "IN THE HUNT", tone: "warn", can: "2nd to 8th",
          players: ["Brett Dillon", "Stacy Michaelsen"],
          notes: ["A win almost certainly does it, landing them anywhere from 2nd to 5th. Only a minimum win combined with a maximum win from Luxor or Shoey knocks them out.",
                  "They can even survive a loss. Taking the top loser slot for 6 points reaches 103, and if Cal Aggie only wins small at 101, Peloton holds 4th while losing the head to head.",
                  "The only team in the promotion fight with a route through defeat."] },
        { name: "Cal Aggie Racing", playing: "trying to earn promotion to the Championship Division.", meta: "5th, 93 pts", tag: "MUST WIN", tone: "bad", can: "3rd to 8th",
          players: ["Andrew Ishak", "Kevin Coolidge"],
          notes: ["Lose and they are out of the automatic places. Best case while losing is 5th, one short.",
                  "Winning is necessary but not sufficient. A small win at 101 could still be beaten if Peloton grabs the 6 point loser slot for 103.",
                  "But there is a back door. Their 78.3 average is the best in the division. Finish 5th with the Championship's 8th place team below them, and the Matchup Position promotes them anyway. Losing a high scoring match could send them up."] },
        { text: "Brett and Andrew lived on the same floor at UC Davis in 2000. So did Stacy and Kevin. Twenty six years later, the four of them are matched up with a promotion place on the line." }),

      M("Luxor Motorsport vs Shoey Time! w/ Max and Danny",
        { name: "Luxor Motorsport", playing: "trying to earn promotion to the Championship Division.", meta: "6th, 85 pts", tag: "MUST WIN BIG", tone: "bad", can: "4th to 9th",
          players: ["Pavly Attalah", "Chris Malek"],
          notes: ["Lose and they are out. Best case while losing is 6th.",
                  "To reach 4th they need close to the maximum 25, reaching 110, plus Peloton to lose and Cal Aggie to win only narrowly."] },
        { name: "Shoey Time! w/ Max and Danny", playing: "trying to earn promotion to the Championship Division.", label: "Shoey Time!", meta: "7th, 82 pts", tag: "MUST WIN BIG", tone: "bad", can: "4th to 9th",
          players: ["Max Reisinger", "Danny Bowers"],
          notes: ["Lose and they are out. Best case while losing is 7th.",
                  "A maximum win reaches 107. The same requirement as Luxor, which makes this a straight shootout for one outside chance."] },
        { text: "Two teams needing the same result, playing each other. Only one of them can have it." }),

      M("HomeworkTubes.Com vs Magic Kingdom Racing",
        { name: "HomeworkTubes.Com", playing: "already promoted, playing for final position.", meta: "3rd, 117 pts", tag: "GOING UP", tone: "good", can: "2nd to 4th",
          players: ["Sam Bottoms", "Grant Wong"],
          notes: ["Up regardless, and saved by the fixture list. The only two teams that could pass them, Peloton and Cal Aggie, are playing each other, so at most one can win."] },
        { name: "Magic Kingdom Racing", playing: "trying to earn promotion to the Championship Division.", meta: "8th, 78 pts", tag: "LONG SHOT", tone: "warn", can: "4th to 9th",
          players: ["Chris Fondacaro", "Larry Noel"],
          notes: ["39 points off the promotion place and somehow still able to reach 4th. The path: beat HomeworkTubes for the maximum 25, reaching 103, while Peloton loses and Cal Aggie wins with only the minimum 8 for 101.",
                  "Anything less and they are done."] },
        { text: "The only team in the league with a domain name, and they are going up on the strength of it. Still no official word on what the tubes are for, or how the homework gets in there.",
          href: "https://homeworktubes.com", hrefLabel: "homeworktubes.com" }),

      M("Meatballs vs Prestissimo Veloce",
        { name: "Meatballs", playing: "already promoted, going for top of the Second Division.", meta: "1st, 143 pts", tag: "GOING UP", tone: "good", can: "1st to 2nd",
          players: ["Anthony Carnesecca", "Maggie Ball"],
          notes: ["Up regardless. Only TNT Roku can catch them, and only with a maximum win while Meatballs score zero. Win and they finish the first half top of the Second Division."] },
        { name: "Prestissimo Veloce", playing: "playing for pride and some practice before the reset.", meta: "10th, 47 pts", tag: "STAYING DOWN", tone: "dead", can: "9th to 12th",
          players: ["Evie Ishak", "Matilda Luton"],
          notes: ["A maximum win reaches 72, below the floor of the eight teams above them.",
                  "Playing for pride, and for a bit of practice before the second half resets everything."] }),

      M("TNT Roku F5 Team vs TJ Premium",
        { name: "TNT Roku F5 Team", playing: "already promoted, with an outside shot at topping the Second Division.", meta: "2nd, 121 pts", tag: "GOING UP", tone: "good", can: "1st to 4th",
          players: ["Andy Thompson", "Matteo Thompson"],
          notes: ["Up regardless. Only three teams can finish above them in any scenario."] },
        { name: "TJ Premium", playing: "playing for pride and a better start to the second half.", meta: "9th, 65 pts", tag: "STAYING DOWN", tone: "dead", can: "6th to 10th",
          players: ["TJ Donato", "Formula5 Bot"],
          notes: ["Even a maximum win only reaches 90 and 6th place. Peloton and Cal Aggie both finish above them no matter what, because one of them wins the head to head and the loser still sits on more points than TJ can reach.",
                  "Playing for pride and a better starting point next half."] }),

      M("Aggie Slipstream vs Scuderia Iskandaraya",
        { name: "Aggie Slipstream", playing: "playing to climb to 9th or 10th and take momentum into the second half.", meta: "11th, 46 pts", tag: "STAYING DOWN", tone: "dead", can: "9th to 12th",
          players: ["Brian Dong", "Dan Patry"],
          notes: ["Maximum reach is 71, short of everyone above them.",
                  "But 9th or 10th is well within range, and climbing two places on the final day is real momentum to carry into the second half."] },
        { name: "Scuderia Iskandaraya", playing: "playing to avoid the wooden spoon.", meta: "12th, 36 pts", tag: "STAYING DOWN", tone: "dead", can: "10th to 12th",
          players: ["Anthony Zamary", "Ramy Stephanos"],
          notes: ["Maximum reach is 61. Lose and they finish last.",
                  "Playing for pride, and to avoid the wooden spoon."] },
        { text: "No surprise where these two are. For Aggie Slipstream, finishing 9th or 10th would be something to build on." }),

      { t: "h", text: "The Matchup Position" },
      { t: "p", text: "One more swap sits on top of the automatic places. If the team that finishes 5th in the Second Division ends the half with a better scoring average than the team that finishes 8th in the Championship, those two trade places as well." },
      { t: "p", text: "So it comes down to two seats and eleven teams who could still occupy them. Here is everyone able to finish 8th in the Championship or 5th in the Second Division, ranked by scoring average as it stands." },
      { t: "chart", note: "Averages move about five points either way in a single race, so Hungary decides it.", rows: [
        { name: "Drivetex", div: "C", avg: 79.2 },
        { name: "East Bay Racing", div: "C", avg: 78.4 },
        { name: "Cal Aggie Racing", div: "2", avg: 78.3 },
        { name: "El Camino Rapido", div: "C", avg: 76.9 },
        { name: "Peloton Aubergine", div: "2", avg: 76.4 },
        { name: "Stalloni 1851", div: "C", avg: 76.1 },
        { name: "Garra Dynamics", div: "C", avg: 74.5 },
        { name: "Cascadia Motorsport", div: "C", avg: 74.0 },
        { name: "Shoey Time!", div: "2", avg: 69.1 },
        { name: "Luxor Motorsport", div: "2", avg: 68.0 },
        { name: "Magic Kingdom Racing", div: "2", avg: 67.5 },
      ]},
      { t: "p", text: "The gap that matters most is right at the top. East Bay and Cal Aggie are separated by a tenth of a point, and they sit on opposite sides of the line." },
    ],
  },
];
